### ISSUE TITLE
Login again

### ISSUE THREAD

**Issue by bullet4790** [MakcStudio/SteamDesktopAuthenticator#10]
При попытках заново залогиниться иногда просит ввести капчу и выдает картинку, на которой невозможно разобрать что-либо. Как это можно обойти?

**Comment by MakcStudio** [comment]
Ну это Steam выдает такое , тут я к сожалению не помощник . 
Каптча обычно просится если очень много попыток входа, если у вас много аккаунтов не используйте их все с одного ip адреса (пк)

**Comment by bullet4790** [comment]
Понял, буду делить. Спасибо!

**Comment by bullet4790** [comment]
Понял, буду делить. Спасибо!
