### ISSUE TITLE
ошибка при сборке исходного кода в visual studio 

### ISSUE THREAD

**Issue by merelenten** [MakcStudio/SteamDesktopAuthenticator#11]
Когда пытаюсь собрать проект то получаю ошибку о не соответствии целевой рабочей среды. Поле с выбором этой настройки пустое и не активное (выбор не предлагается). Как мне решить эту проблему ?
![00](https://github.com/MakcStudio/SteamDesktopAuthenticator/assets/138281551/b25bb9f0-3f54-4b16-a1f3-23c88a8ab7ed)

**Comment by MakcStudio** [comment]
Попробуйте проектный файл руками открыть через текстовый редактор. Или установите .net 5.0 который просят

**Comment by merelenten** [comment]
Спасибо, сработало с значением <TargetFramework>netstandard2.0</TargetFramework> но теперь появилась другая 
![000](https://github.com/MakcStudio/SteamDesktopAuthenticator/assets/138281551/c8d5ce4f-5bd7-4f2e-a073-093e816d43cd)

**Comment by MakcStudio** [comment]
Что другая?) я ошибок не вижу. 
Зачем вы его компилируете руками, если нет необходимых знаний . В проекте прикреплен готовый архив с релизом , просто скачайте и пользуйтесь

**Comment by merelenten** [comment]
Если код без ошибок то и компиляция проходит без проблем и глубинные знания тут совсем не причём. 
К примеру взял код SDA у джеса и скомпелировал без всяких проблем, с вашим так не получается вот и обратился за помощью.

**Comment by MakcStudio** [comment]
Однако, видимо не все так просто, раз у вас не получается. В любом случае я не вижу никаких ошибок , вы судя по всему компилируете просто что-то не правильно

**Comment by merelenten** [comment]
На последнем скрине ошибок нет но и компиляция не происходит. Там пропуск и в выходном каталоге bin\x64\Debug\ пусто.

**Comment by MakcStudio** [comment]
Может вы компилируете библиотеку, а не сам sda?

**Comment by merelenten** [comment]
Сборка - собрать решение. 
Сборка начата…
1>------ Сборка начата: проект: SteamAuth, Конфигурация: Debug Any CPU ------
1>SteamAuth -> C:\Users\user\Desktop\sda\lib\SteamAuth\bin\Debug\netstandard2.0\SteamAuth.dll
2>------ Пропуск сборки: проект: Steam Desktop Authenticator ------
2> 
========== Сборка: успешно: 1, с ошибками: 0, без изменений: 0, пропущено: 1 ==========

**Comment by MakcStudio** [comment]
Ну тут написано, что вы собираете библиотеку , а не sda

**Comment by merelenten** [comment]
Вероятно всё дело в конфигурации сборки. Все действия в studio одни и те же а результат разный на проектах.

**Comment by MakcStudio** [comment]
Просто для этого нужны хотя бы небольшие знания. Просто скачайте собранный вариант и все, не очень понятно что вы хотите поменять, если сами скомпилируете проект

**Comment by merelenten** [comment]
Разве не для этого и предоставляется исходный код чтобы пользователь сам его мог скомпелировать. 
Ссылаться на знания это всегда очень удобно вот только проблем никогда не решает. По такой логике все кто имеет авто должен как минимум обязательно разбираться в двигателях внутреннего сгорания. 
Чтобы убрать ошибку в компеляции уже пришлось в ручную править файл, вряд ли это правильно для релиза.

**Comment by MakcStudio** [comment]
Вам пришлось править файл, потому что у вас стоит sdk не той версии.

Как раз чтобы иметь машину не нужно разбираться в двигателе, а так же не нужно собирать ее вручную, если нет соответствующих знаний. Для этого есть специальные люди.

К сожалению, я не смогу помочь вам с компиляцией в issue на гитхаб. Если есть большое желание все же скомпилировать самому, обратитесь на фриланс , я думаю за небольшую сумму там вам скомпилируют код. Но я бы на вашем месте скачал готовый, потому что то, что вам скомпилируют - не факт что не добавят что-то от себя (вредоносное)
