### ISSUE TITLE
Way to sort accounts

### ISSUE THREAD

**Issue by leo90012** [MakcStudio/SteamDesktopAuthenticator#2]
Hey my accounts are all mixed up is there a way to sort it like the official one where all are sort by alphabetical order, sorry if this is a dumb question but i can't find it

**Comment by MakcStudio** [comment]
Unfortunately not, as it is not the latest version of the sda . Perhaps in the future. Alternatively you can use search.

> Hey my accounts are all mixed up is there a way to sort it like the official one where all are sort by alphabetical order, sorry if this is a dumb question but i can't find it
