### ISSUE TITLE
Add account

### ISSUE THREAD

**Issue by galo-gamboa** [MakcStudio/SteamDesktopAuthenticator#3]
Hello, if you would be so kind, could you tell me the steps to add an account? because I don't understand Russian and I've been using this application for a short time, thanks a lot.

**Comment by galo-gamboa** [comment]
It makes you log in the account, you get a message to the phone number and then what's next?

**Comment by MakcStudio** [comment]
You can use any screenshot translator, in fact, there is nothing complicated. Press add account and then just always press ok or next and enter what you are asked
