### ISSUE TITLE
most of accounts are not working after changing proxy

### ISSUE THREAD

**Issue by Kottifen** [MakcStudio/SteamDesktopAuthenticator#5]
I am a CounterBot user, thanks u a lot for reworking SDA , u did a great job on it 
If possible, please fix series of issues after setting a new proxy, it caused account almost not work for trades

**Comment by Kottifen** [comment]
Also, I found out it didn't work for multiple accounts, only one account which u select will work for confirming trades
And one more issue is that if u set a short checking time gap ( idk how to describe this function in eng) like 20 sec for multiple accounts , SDA always crash

**Comment by MakcStudio** [comment]
Today I uploaded a new release 1.0.2.2 . Try it, it seems to be fixed the problem you wrote about

> Also, I found out it didn't work for multiple accounts, only one account which u select will work for confirming trades
> And one more issue is that if u set a short checking time gap ( idk how to describe this function in eng) like 20 sec for multiple accounts , SDA always crash

**Comment by Kottifen** [comment]
Just keep the same IP on SDA account and the account on any client which build from Steam Auth，then IP problem gonna solve.
Anyway，it lets accounts safely working again，thx a lot to https://github.com/MakcStudio
