### ISSUE TITLE
SCAM ALERT

### ISSUE THREAD

**Issue by FusionJura** [MakcStudio/SteamDesktopAuthenticator#6]
THIS REPOSITORY IS SCAM

Builded version is MALICIOUS but source code is clean!

**Comment by FusionJura** [comment]
It is contacting multiple IP endpoints (not steam)

23.54.112.231
140.82.121.4
92.122.104.90

https://www.virustotal.com/gui/file/723625407a17f031aaabd3aeb9950834f9582cd667dc20bdc1b3cec91dd52d67/community

**Comment by MakcStudio** [comment]
You can compile it by hand and use it. I assure you, the compiled version is the same as in the source code. If you do it yourself, you will also be detected by antiviruses. I do not know what they rely on when they show viruses in it. I checked the archive and the exe on virustotal and everything is clean there (one detection by a noname antivirus)

**Comment by MakcStudio** [comment]
I don't really understand what ip you sent, what is it? Where did you find it?)

**Comment by therepower** [comment]
these are cdn servers of steam, and one is github

**Comment by MakcStudio** [comment]
Haha ) nice. Thank you for the information, at least one person understands the subject

**Comment by FusionJura** [comment]
> Haha ) nice. Thank you for the information, at least one person understands the subject

sorry for attacking your git project, but you have to understand my perspective.
The project stopped working and suddenly new git projects appeared that supposedly fix the problem.
This is normally an instant red flag, because users are desperate for an authenticator that works, they'll download anything.

**Comment by BinAlexme** [comment]
it is logical that this is easy money. also most users are too gullible in projects. for example, I was not very hurt by the fact that I can not transfer the exchange. I have an Authenticator on the offline so that they don’t bring an update that can only do harm
