### ISSUE TITLE
Scam

### ISSUE THREAD

**Issue by DaffyExtra** [MakcStudio/SteamDesktopAuthenticator#7]
**The builded version has code which contacts ips which is not steam pls do not use this.**

https://github.com/MakcStudio/SteamDesktopAuthenticator/issues/6

**Comment by MakcStudio** [comment]
Can you tell me how you determined this?
There is nothing like that and the compiled version is compiled from the same sources. You can decompile it without problems and check the decompiled code

**Comment by DaffyExtra** [comment]
> Can you tell me how you determined this? There is nothing like that and the compiled version is compiled from the same sources. You can decompile it without problems and check the decompiled code

https://www.virustotal.com/gui/file/723625407a17f031aaabd3aeb9950834f9582cd667dc20bdc1b3cec91dd52d67/community

**Comment by MakcStudio** [comment]
Great antiviruses) let me tell you a secret, sometimes this kind of crap has false positive detections. I do not force you to do anything, but the official surrender also has detections
