### ISSUE TITLE
Logging in error: GeneralFailure

### ISSUE THREAD

**Issue by Necromancerx9** [MakcStudio/SteamDesktopAuthenticator#9]
Hi, I imported my account from old sda(Jessecar96) to this (MakcStudio) and still got this error, did I wrong something? 
![image](https://github.com/MakcStudio/SteamDesktopAuthenticator/assets/66694283/5accba2c-6b01-4c9f-b1d0-c2921eb116d2)

**Comment by MakcStudio** [comment]
It's strange, everything works there. Have you tried it several times?

Try connecting to another wifi network (maybe give out from your phone) and try again

**Comment by Necromancerx9** [comment]
Yes, I have just tried in mobile internet but still get error, I only download Release.1.0.2.2.zip and import, do i forget something?

**Comment by MakcStudio** [comment]
I don't think so, nothing has been forgotten.

**Comment by Necromancerx9** [comment]
Oh, I solved the problem, my friend change his steam guard to mobile without talking to me, I tried my account works well, thank you for supporting me. :D
